### ISSUE TITLE
Incorrect length for some emojis

### ISSUE THREAD

**Issue by sallar** [sindresorhus/string-length#1]
Hi there,
the library returns incorrect length:

``` js
len("❤️"); // 2
len("👊🏽"); // 2
```

I don’t seem to be able to find a solution for this in ANY library except lodash which has a complicated regex...

**Comment by sallar** [comment]
I fixed this problem in my own library using a regex borrowed from lodash...
https://github.com/sallar/stringz

**Comment by revelt** [comment]
If `stringz` issue [27](https://github.com/sallar/stringz/issues/27) does come through, we could replace aging `astral-regex` with that regex and results would be correct again in all the cases.

**Comment by Richienb** [comment]
Here's Lodash's strategy: https://github.com/lodash/lodash/blob/master/.internal/unicodeSize.js

**Comment by revelt** [comment]
In general, _string length_ is `string.length`. If we start to calculate the **code point count** and yet call that _a string length_ — that's a mistake. This package should have been called _code point count_ to match the promise in the readme. 

@sindresorhus If I may advise, if I was a maintainer of this program, I'd propose to **can this project** and leave emoji length calculation to specialist packages with proper support where people seriously spend time on Unicode and are able update the program to cater new-fangled emoji that is released continuously. This is not a quick one-liner package!

**Comment by Richienb** [comment]
string-length was made to count what the **logically counted** length of a string is. I've extracted part of Lodash's strategy which is considerably more maintained into another module. I'll open a PR for version 4.

**Comment by revelt** [comment]
I understand, yet terminology conundrum is still here, it's not _string length_, it's _code point count_
