### ISSUE TITLE
Use `Intl.Segmenter` when available?

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/string-length#14]
Investigate using https://github.com/tc39/proposal-intl-segmenter when/if it becomes available.

```js
new Intl.Segmenter('en', {granularity: 'grapheme'});
```

**Comment by Richienb** [comment]
By using a [ponyfill](https://github.com/surferseo/intl-segmenter-polyfill) as a fallback when `Intl.Segmenter` is not available, it is possible to split a string by each character: https://github.com/Richienb/split-chars

**Comment by sindresorhus** [comment]
I don't want to bring in a polyfill and all the potential problems and bloat that comes with that. The current code works ok, so we can just wait until it becomes available in Node.js.

**Comment by Richienb** [comment]
Ok. Looks like `Intl.Segmenter` will be available in Node.js 16. [[1](https://tech-en.netlify.app/articles/en518900/index.html)]

**Comment by Mini-ghost** [comment]
Should we mention in the Readme that FireFox does not currently support `Intl.Segmenter`? After all, this API is being used in the source code.
